source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SDWebImage', '~> 3.7.6'
pod 'Reachability', '~> 3.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'AFNetworking', '~> 3.1'
pod 'MJRefresh', '~> 3.1'
pod 'FMDB', '~> 2.6.2'
pod 'ViewDeck', '~> 2.4'